name: Test

on: [push, pull_request]

jobs:
  docker:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Build Docker image
      run: docker build -t my-jupyter-app .
    
    - name: Test Docker image
      run: |
        docker run -d --name test-container -p 8888:8888 my-jupyter-app
        sleep 30  # Attendre 30 secondes pour que Jupyter démarre
        echo "Container logs:"
        docker logs test-container
        echo "Searching for Jupyter in logs:"
        docker logs test-container | grep -i "jupyter" || true
        echo "Container status:"
        docker inspect test-container --format '{{.State.Status}}'
        echo "Container exit code:"
        docker inspect test-container --format '{{.State.ExitCode}}'
    
    - name: Check Jupyter startup
      run: |
        max_attempts=10
        attempt=1
        while [ $attempt -le $max_attempts ]; do
          if docker logs test-container | grep -q "Jupyter Server.*is running at"; then
            echo "Jupyter started successfully"
            exit 0
          fi
          echo "Attempt $attempt: Jupyter not started yet, waiting..."
          sleep 5
          attempt=$((attempt+1))
        done
        echo "Jupyter failed to start after $max_attempts attempts"
        docker logs test-container
        exit 1
    
    - name: Stop Docker container
      if: always()
      run: docker stop test-container