name: Test

on: [push, pull_request]

jobs:
  docker:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Build Docker image
      run: docker build -t my-jupyter-app .
    
    - name: Test Docker image
      run: |
        docker run -d --name test-container -p 8888:8888 my-jupyter-app
        sleep 30
        echo "Container logs:"
        docker logs test-container
        echo "Searching for Jupyter in logs:"
        docker logs test-container | grep -i "jupyter" || true
        echo "Container status:"
        docker inspect test-container --format '{{.State.Status}}'
        echo "Container exit code:"
        docker inspect test-container --format '{{.State.ExitCode}}'
        docker stop test-container
      continue-on-error: true
    
    - name: Check Jupyter startup
      run: |
        if docker logs test-container | grep -qi "jupyter.*is running at"; then
          echo "Jupyter started successfully"
          exit 0
        else
          echo "Jupyter failed to start"
          exit 1
        fi